name: Deploy Backend

on:
  push:
    branches: [ main ]   # runs only when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Recreate .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Run build
        run: npm run build

      # OPTIONAL: if you want to run your backend inside GitHub Action before deploy
      # - name: Run tests
      #   run: npm test
